"use client";

import { useState, useEffect, useCallback } from "react";
import { 
  X, 
  Download, 
  Share2, 
  FileText,
  Loader2,
  CheckCircle,
  MessageCircle,
  RefreshCw,
  BookOpen,
  GraduationCap,
  Stethoscope,
  Info
} from "lucide-react";
import { 
  generateEnhancedPDFReport, 
  downloadPDF,
  LITERACY_CONFIGS,
  type MedicalLiteracyLevel 
} from "@/lib/pdf-report-v2";

interface AgentResponse {
  response: string;
  citations: string[];
  toolsUsed: string[];
}

interface PDFPreviewModalV2Props {
  isOpen: boolean;
  onClose: () => void;
  consensus: string;
  agentResponses: Record<string, AgentResponse>;
  caseInfo: {
    cancerSite?: string;
    stage?: string;
    tnm?: string;
    documentCount?: number;
  };
}

// WhatsApp icon as SVG
function WhatsAppIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
    </svg>
  );
}

// Literacy level icons
const LITERACY_ICONS: Record<MedicalLiteracyLevel, typeof BookOpen> = {
  simple: BookOpen,
  standard: GraduationCap,
  technical: Stethoscope,
};

// Literacy level colors
const LITERACY_COLORS: Record<MedicalLiteracyLevel, string> = {
  simple: 'from-emerald-500 to-teal-600',
  standard: 'from-blue-500 to-indigo-600',
  technical: 'from-purple-500 to-pink-600',
};

export function PDFPreviewModalV2({ 
  isOpen, 
  onClose, 
  consensus,
  agentResponses,
  caseInfo 
}: PDFPreviewModalV2Props) {
  const [literacyLevel, setLiteracyLevel] = useState<MedicalLiteracyLevel>('standard');
  const [pdfBlob, setPdfBlob] = useState<Blob | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(false);

  // Generate PDF when modal opens or literacy level changes
  const generatePDF = useCallback(async () => {
    if (!consensus) return;
    
    setIsGenerating(true);
    
    try {
      const blob = await generateEnhancedPDFReport(
        consensus,
        agentResponses,
        caseInfo,
        literacyLevel
      );
      setPdfBlob(blob);
      
      // Create URL for preview
      if (pdfUrl) {
        URL.revokeObjectURL(pdfUrl);
      }
      const url = URL.createObjectURL(blob);
      setPdfUrl(url);
    } catch (error) {
      console.error('PDF generation error:', error);
    } finally {
      setIsGenerating(false);
    }
  }, [consensus, agentResponses, caseInfo, literacyLevel, pdfUrl]);

  // Generate on open and literacy change
  useEffect(() => {
    if (isOpen && consensus) {
      generatePDF();
    }
  }, [isOpen, literacyLevel, consensus]);

  // Cleanup URL on close
  useEffect(() => {
    return () => {
      if (pdfUrl) {
        URL.revokeObjectURL(pdfUrl);
      }
    };
  }, [pdfUrl]);

  if (!isOpen) return null;

  const handleDownload = () => {
    if (!pdfBlob) return;
    const filename = `tumor-board-report-${literacyLevel}-${new Date().toISOString().split('T')[0]}.pdf`;
    downloadPDF(pdfBlob, filename);
  };

  const handleWhatsAppShare = async () => {
    setIsSharing(true);
    
    try {
      const levelLabel = LITERACY_CONFIGS[literacyLevel].label;
      const message = encodeURIComponent(
        `Virtual Tumor Board Report\n\n` +
        `Cancer: ${caseInfo.cancerSite || 'Not specified'}\n` +
        `Stage: ${caseInfo.stage || 'Not determined'}\n` +
        `Report Type: ${levelLabel}\n\n` +
        `This AI-generated report contains multi-specialist oncology recommendations. ` +
        `Please review with your treating oncologist.\n\n` +
        `Generated by Virtual Tumor Board\n` +
        `https://virtual-tumor-board-production.up.railway.app`
      );
      
      // Try Web Share API first
      if (navigator.share && pdfBlob) {
        const file = new File([pdfBlob], 'tumor-board-report.pdf', { type: 'application/pdf' });
        
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
          await navigator.share({
            files: [file],
            title: 'Tumor Board Report',
            text: `Tumor Board Report (${levelLabel}) for ${caseInfo.cancerSite || 'Cancer'} case`,
          });
          setShareSuccess(true);
          setTimeout(() => setShareSuccess(false), 3000);
          return;
        }
      }
      
      // Fallback to WhatsApp URL
      window.open(`https://wa.me/?text=${message}`, '_blank');
      setShareSuccess(true);
      setTimeout(() => setShareSuccess(false), 3000);
      
    } catch (error) {
      console.error('Share error:', error);
      const message = encodeURIComponent(
        `Virtual Tumor Board Report for ${caseInfo.cancerSite || 'Cancer'}\n\n` +
        `View at: https://virtual-tumor-board-production.up.railway.app`
      );
      window.open(`https://wa.me/?text=${message}`, '_blank');
    } finally {
      setIsSharing(false);
    }
  };

  const handleNativeShare = async () => {
    if (!navigator.share) {
      handleWhatsAppShare();
      return;
    }

    try {
      if (pdfBlob) {
        const file = new File([pdfBlob], 'tumor-board-report.pdf', { type: 'application/pdf' });
        
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
          await navigator.share({
            files: [file],
            title: 'Tumor Board Report',
            text: `Virtual Tumor Board Report for ${caseInfo.cancerSite || 'Cancer'}`,
          });
          return;
        }
      }
      
      await navigator.share({
        title: 'Tumor Board Report',
        text: `Virtual Tumor Board Report for ${caseInfo.cancerSite || 'Cancer'}`,
        url: window.location.href,
      });
    } catch (error) {
      console.log('Share cancelled or failed');
    }
  };

  const config = LITERACY_CONFIGS[literacyLevel];
  const LiteracyIcon = LITERACY_ICONS[literacyLevel];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="bg-slate-900 rounded-2xl border border-slate-700 w-full max-w-5xl max-h-[95vh] flex flex-col overflow-hidden shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-700 bg-gradient-to-r from-indigo-600/20 to-purple-600/20">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-white">Tumor Board Report</h2>
              <p className="text-sm text-slate-400">
                {caseInfo.cancerSite || 'Cancer'} - {caseInfo.stage || 'Stage TBD'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5 text-slate-400" />
          </button>
        </div>

        {/* Literacy Level Selector */}
        <div className="px-6 py-4 border-b border-slate-700/50 bg-slate-800/30">
          <div className="flex items-center gap-2 mb-3">
            <Info className="w-4 h-4 text-indigo-400" />
            <span className="text-sm font-medium text-slate-300">
              Choose report complexity for your needs:
            </span>
          </div>
          
          <div className="grid grid-cols-3 gap-3">
            {(Object.keys(LITERACY_CONFIGS) as MedicalLiteracyLevel[]).map((level) => {
              const levelConfig = LITERACY_CONFIGS[level];
              const Icon = LITERACY_ICONS[level];
              const isSelected = literacyLevel === level;
              
              return (
                <button
                  key={level}
                  onClick={() => setLiteracyLevel(level)}
                  disabled={isGenerating}
                  className={`relative p-4 rounded-xl border-2 transition-all text-left ${
                    isSelected 
                      ? `border-indigo-500 bg-indigo-500/10` 
                      : 'border-slate-700 hover:border-slate-600 bg-slate-800/50 hover:bg-slate-800'
                  } ${isGenerating ? 'opacity-50 cursor-not-allowed' : ''}`}
                >
                  {/* Selection indicator */}
                  {isSelected && (
                    <div className="absolute top-2 right-2">
                      <CheckCircle className="w-5 h-5 text-indigo-400" />
                    </div>
                  )}
                  
                  {/* Icon */}
                  <div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${LITERACY_COLORS[level]} flex items-center justify-center mb-2`}>
                    <Icon className="w-5 h-5 text-white" />
                  </div>
                  
                  {/* Label */}
                  <h4 className={`font-semibold mb-1 ${isSelected ? 'text-white' : 'text-slate-300'}`}>
                    {levelConfig.label}
                  </h4>
                  
                  {/* Description */}
                  <p className="text-xs text-slate-400 line-clamp-2">
                    {levelConfig.description}
                  </p>
                </button>
              );
            })}
          </div>
          
          {/* Current selection indicator */}
          <div className="mt-3 flex items-center gap-2 text-sm">
            <span className="text-slate-500">Selected:</span>
            <span className={`px-2 py-0.5 rounded-full bg-gradient-to-r ${LITERACY_COLORS[literacyLevel]} text-white text-xs font-medium`}>
              {config.label}
            </span>
            {isGenerating && (
              <span className="flex items-center gap-1 text-indigo-400">
                <RefreshCw className="w-3 h-3 animate-spin" />
                Updating preview...
              </span>
            )}
          </div>
        </div>

        {/* PDF Preview */}
        <div className="flex-1 overflow-hidden bg-slate-950 relative">
          {isGenerating && (
            <div className="absolute inset-0 bg-slate-950/80 flex items-center justify-center z-10">
              <div className="flex flex-col items-center gap-3">
                <Loader2 className="w-10 h-10 text-indigo-400 animate-spin" />
                <span className="text-slate-300 text-sm">Generating {config.label} report...</span>
              </div>
            </div>
          )}
          
          {pdfUrl ? (
            <iframe
              src={`${pdfUrl}#toolbar=0&view=FitH`}
              className="w-full h-full min-h-[350px]"
              title="PDF Preview"
            />
          ) : (
            <div className="flex items-center justify-center h-full min-h-[350px]">
              <Loader2 className="w-8 h-8 text-indigo-400 animate-spin" />
            </div>
          )}
        </div>

        {/* Action Buttons */}
        <div className="px-6 py-4 border-t border-slate-700 bg-slate-900/50">
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
            {/* Download Button */}
            <button
              onClick={handleDownload}
              disabled={!pdfBlob || isGenerating}
              className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-medium rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Download className="w-5 h-5" />
              Download {config.label} PDF
            </button>

            {/* WhatsApp Share Button */}
            <button
              onClick={handleWhatsAppShare}
              disabled={isSharing || !pdfBlob}
              className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-[#25D366] hover:bg-[#20BD5A] text-white font-medium rounded-xl transition-all disabled:opacity-50"
            >
              {isSharing ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : shareSuccess ? (
                <CheckCircle className="w-5 h-5" />
              ) : (
                <WhatsAppIcon className="w-5 h-5" />
              )}
              {shareSuccess ? 'Shared!' : 'Share on WhatsApp'}
            </button>

            {/* Native Share Button */}
            <button
              onClick={handleNativeShare}
              disabled={!pdfBlob}
              className="sm:flex-none flex items-center justify-center gap-2 px-4 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 font-medium rounded-xl transition-all disabled:opacity-50"
            >
              <Share2 className="w-5 h-5" />
              <span className="sm:hidden">Share</span>
            </button>
          </div>

          {/* Hints */}
          <div className="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-xs text-slate-500">
            <span>Share with your doctor or family</span>
            <span className="hidden sm:inline">-</span>
            <span>Report adapts to selected reading level</span>
          </div>
        </div>
      </div>
    </div>
  );
}
